# railway.toml
[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 600 
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.env]
NODE_ENV = "production"
PORT = "3000"