# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - api-scrapper-market

on:
  push:
    branches:
      - backend
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Change to scraper directory
        run: cd scraper

      - name: npm install, build, and test
        run: |
          cd scraper  # Cambia a la carpeta del proyecto
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: |
          cd scraper  # Cambia a la carpeta del proyecto
          zip -r release.zip .  # Zipa todo el contenido de la carpeta

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: scraper/release.zip  # Ajusta el path para el artefacto

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2DD8D41D7BCE4A279D27B54A06C55EBC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_43759AF487BD47D199F559B5E048FAE3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_56022BA4C91548FF9707DDE181AEA5F6 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-scrapper-market'
          slot-name: 'Production'
          package: .
          
