name: Scrape and Store Historical Data

on:
  schedule:
    # Ejecutar una vez al día a las 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: |
          cd go-test
          go mod download

      - name: Run scrapers
        run: |
          cd go-test
          echo "Running Dia scraper..."
          cd dia
          go run dia_scraper.go
          echo "Running Jumbo scraper..."
          cd ..
          echo "directorio inicial"
          cd jumbo
          go run jumbo_scraper.go

      - name: Configurar token para autenticación
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Verificar cambios
        id: verify-changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if there are changes
        if: steps.verify-changes.outputs.changes == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add go-test/data/daily/
          git commit -m "📊 Update historical data - $(date +'%Y-%m-%d %H:%M:%S')"
          git push
