on:
  schedule:
    - cron: '0 0 */1 * *'  # Ejecutar cada día a medianoche
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  scrape-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Run Scraper
      run: |
        cd scraper
        npm install
        node scraper.js

    - name: Deploy to Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} --account-key ${{ secrets.AZURE_STORAGE_KEY }} -d '$web' -s ./scraper --overwrite

    - name: Build React App
      run: |
        cd frontend
        npm install
        npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/dist